# Shared configuration for both client and server

SCREEN_WIDTH = 400
SCREEN_HEIGHT = 600
PUCK_RADIUS = 20
PUCK_SPEED = 5
PLAYER_INITIAL_X = {1: 100, 2: 700}
PLAYER_INITIAL_Y = SCREEN_HEIGHT // 2
WINNING_SCORE = 5
GOAL_WIDTH = 200
GOAL_X_RANGE = ((SCREEN_WIDTH - GOAL_WIDTH) // 2, (SCREEN_WIDTH + GOAL_WIDTH) // 2)
